### PR TITLE
fix: autocompletion in import path

### LINKED ISSUE #286: File suggestion is broken on imports

### LINKED ISSUE #507: The import path completion always remove the existing closing quotes
Image

How about change the code like this:

Image

### PR DESCRIPTION
**Pull request by Paulalex85**
Will resolve #507 and fix #286

### CODE REVIEW

File: src/main/kotlin/me/serce/solidity/lang/completion/contributors.kt [hunk 1]
```diff
@@ -106,35 +106,72 @@ class SolContextCompletionContributor : CompletionContributor(), DumbAware {
...
-                .map { LookupElementBuilder.create("\"$dirText${it.name}").withIcon(SolidityIcons.FILE_ICON) } +
-               humpFiles
-                 .map {
-                   val rel = if (it.path.contains("node_modules/")) it.path.substringAfter("node_modules/")
-                   else (VfsUtil.findRelativePath(curFile.parent, it, '/')?.let { if (!it.startsWith(".")) "./$it" else it } ?: it.path)
-                   LookupElementBuilder.create("\"$rel").withLookupString("\"${it.name}").withIcon(SolidityIcons.FILE_ICON)
-                 }
-              result.addAllElements(elements)
+                .map {
+                  LookupElementBuilder.create(prefix + path + it.name)
```
Comment (SerCeMan) [inline src/main/kotlin/me/serce/solidity/lang/completion/contributors.kt]: It seems that the new path construction approach is causing the nested relative paths to not be completed as expected. 

For example, the following test fails:
```patch
Subject: [PATCH] test
---
Index: src/test/kotlin/me/serce/solidity/lang/completion/SolImportParentPathCompletionTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/test/kotlin/me/serce/solidity/lang/completion/SolImportParentPathCompletionTest.kt b/src/test/kotlin/me/serce/solidity/lang/completion/SolImportParentPathCompletionTest.kt
--- a/src/test/kotlin/me/serce/solidity/lang/completion/SolImportParentPathCompletionTest.kt	(revision e0ddbfd16805d3412baae34d11e36b1c393e298f)
+++ b/src/test/kotlin/me/serce/solidity/lang/completion/SolImportParentPathCompletionTest.kt	(date 1762646752498)
@@ -59,5 +59,16 @@
         )
     }
 
+    fun testImportCompletionPreservesMultipleParentSegments() {
+        myFixture.configureByFile("interfacesLocal/IERC20Local.sol")
+        myFixture.configureByFile("nested/feature/MultiParentImport.sol")
+        myFixture.completeBasic()
+        val lookupStrings = myFixture.lookupElementStrings
+            ?: error("No lookup elements for import completion")
+        assertTrue(
+            lookupStrings.any { it.contains("../../interfacesLocal/IERC20Local.sol") }
+        )
+    }
+
     override fun getTestDataPath() = "src/test/resources/fixtures/importCompletion/lib/"
-}
\ No newline at end of file
+}
Index: src/test/resources/fixtures/importCompletion/lib/nested/feature/MultiParentImport.sol
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/test/resources/fixtures/importCompletion/lib/nested/feature/MultiParentImport.sol b/src/test/resources/fixtures/importCompletion/lib/nested/feature/MultiParentImport.sol
new file mode 100644
--- /dev/null	(date 1762646461120)
+++ b/src/test/resources/fixtures/importCompletion/lib/nested/feature/MultiParentImport.sol	(date 1762646461120)
@@ -0,0 +1,6 @@
+// SPDX-License-Identifier: MIT
+pragma solidity ^0.8.26;
+
+import "../../interfacesLocal/IE<caret>";
+
+contract MultiParentImport {}
Index: src/test/resources/fixtures/importCompletion/lib/interfacesLocal/IERC20Local.sol
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/test/resources/fixtures/importCompletion/lib/interfacesLocal/IERC20Local.sol b/src/test/resources/fixtures/importCompletion/lib/interfacesLocal/IERC20Local.sol
new file mode 100644
--- /dev/null	(date 1762646461119)
+++ b/src/test/resources/fixtures/importCompletion/lib/interfacesLocal/IERC20Local.sol	(date 1762646461119)
@@ -0,0 +1,6 @@
+// SPDX-License-Identifier: MIT
+pragma solidity ^0.8.26;
+
+interface IERC20Local {
+    function totalSupply() external view returns (uint256);
+}
Index: src/test/resources/fixtures/importCompletion/lib/nested/feature/MultiParentImport_after.sol
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/test/resources/fixtures/importCompletion/lib/nested/feature/MultiParentImport_after.sol b/src/test/resources/fixtures/importCompletion/lib/nested/feature/MultiParentImport_after.sol
new file mode 100644
--- /dev/null	(date 1762646461120)
+++ b/src/test/resources/fixtures/importCompletion/lib/nested/feature/MultiParentImport_after.sol	(date 1762646461120)
@@ -0,0 +1,6 @@
+// SPDX-License-Identifier: MIT
+pragma solidity ^0.8.26;
+
+import "../../interfacesLocal/IERC20Local.sol";
+
+contract MultiParentImport {}
```

**Review by SerCeMan — APPROVED** [review]
Thanks! While testing, I noticed that we don't really support `'` imports, while Solidity supports it so that's something I think we'll need to look into.
