### PR TITLE
fix #543: address commenter issues

### LINKED ISSUE #543: Block comment autocomplete generates wrong result
In any *.java file: 
1. Enter /**/
2. Move cursor between *: /*|*/
3. Press <Enter>
and got wrong result:
```
/*
*  * 
*  */*/
```

### PR DESCRIPTION
**Pull request by SerCeMan**
This PR addresses issues raised in https://github.com/intellij-solidity/intellij-solidity/issues/543

### CODE REVIEW

**Review by Paulalex85 — COMMENTED** [review]
Works well except for the use case `/*|*/` and `/*|/` but it's up to you if you think it's not a bug

File: src/test/kotlin/me/serce/solidity/ide/typing/SolBlockCommentEnterHandlerTest.kt [hunk 1]
```diff
@@ -53,6 +64,17 @@ class SolBlockCommentEnterHandlerTest : SolTestBase() {
     myFixture.type('\n')
   }
 
+  fun testBlockCommentContinuationFromSingleLine() = checkByText(
+    "/*<caret>*/",
```
Comment (SerCeMan) [inline src/test/kotlin/me/serce/solidity/ide/typing/SolBlockCommentEnterHandlerTest.kt]: @Paulalex85 I think this is the `/*|*/` you mentioned? Unless I misunderstood it?
