### PR TITLE
fix #283: fix base name element resolution

### LINKED ISSUE #283: java.lang.IllegalStateException: unable to extract reference name element from SolFunctionCallExpressionImpl(FUNCTION_CALL_EXPRESSION)
Plugin throw exception on next code:
```
pragma solidity ^0.8.0;

library MathLib {
    function _a(uint256 val) internal pure returns (uint256 res){
         res = val * 2;
    }
    
    function _b(uint256 val) internal pure returns (uint256 res){
         res = val / 2;
    }
}

contract Tst {
    function ff(uint256 val) external pure returns (uint256){
        val = MathLib._a(val);
        return 
            (val == 100 ? MathLib._a : MathLib._b)(
                val
            );
    }
}
```

Found in Balancer code https://github.com/balancer-labs/balancer-v2-monorepo/blob/master/pkg/pool-linear/contracts/LinearPool.sol#L276-L282

Exception:
```
java.lang.IllegalStateException: unable to extract reference name element from SolFunctionCallExpressionImpl(FUNCTION_CALL_EXPRESSION) -> SolSeqExpressionImpl(SEQ_EXPRESSION)
	at me.serce.solidity.lang.psi.impl.SolFunctionCallMixin.getBaseAndReferenceNameElement(mixins.kt:286)
	at me.serce.solidity.lang.psi.impl.SolFunctionCallMixin.getReferenceNameElement(mixins.kt:294)
	at me.serce.solidity.lang.resolve.ref.SolFunctionCallReference.calculateDefaultRangeInElement(refs.kt:92)
	at com.intellij.psi.PsiReferenceBase.getRangeInElement(PsiReferenceBase.java:90)
	at com.intellij.psi.ReferenceRange.getRanges(ReferenceRange.java:20)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.addReferences(SharedPsiElementImplUtil.java:66)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.findReferenceAt(SharedPsiElementImplUtil.java:33)
	at com.intellij.psi.impl.SharedPsiElementImplUtil.findReferenceAt(SharedPsiElementImplUtil.java:51)
	at com.intellij.psi.impl.PsiElementBase.findReferenceAt(PsiElementBase.java:86)
	at com.intellij.psi.AbstractFileViewProvider.findReferenceAt(AbstractFileViewProvider.java:238)
	at com.intellij.psi.SingleRootFileViewProvider.findReferenceAt(SingleRootFileViewProvider.java:224)
	at com.intellij.psi.impl.source.PsiFileImpl.findReferenceAt(PsiFileImpl.java:526)
	at com.intellij.codeInsight.intention.impl.ConvertAbsolutePathToRelativeIntentionAction.isAvailable(ConvertAbsolutePathToRelativeIntentionAction.java:48)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.availableFor(ShowIntentionActionsHandler.java:157)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.lambda$getActionsToShow$1(ShowIntentionsPass.java:336)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseBetweenHostAndInjected(ShowIntentionActionsHandler.java:190)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:335)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:240)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:56)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:400)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1096)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:393)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:392)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:368)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:366)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:188)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

### PR DESCRIPTION
**Pull request by SerCeMan**

### CODE REVIEW

File: src/main/kotlin/me/serce/solidity/lang/psi/impl/mixins.kt [hunk 1]
```diff
@@ -270,28 +270,31 @@ abstract class SolStructDefMixin : SolStubbedNamedElementImpl<SolStructDefStub>,
...
+        expr.identifier!!
       is SolFunctionCallExpression ->
-        Pair(expr.expression, expr.firstChild)
+        expr.firstChild
       is SolIndexAccessExpression ->
-        Pair(expr.expressionList.first(), expr.firstChild)
+        expr.firstChild
       is SolNewExpression ->
-        Pair(expr, expr.typeName as PsiElement)
-      else -> throw IllegalStateException("unable to extract reference name element from $this")
```
Comment (SerCeMan) [inline src/main/kotlin/me/serce/solidity/lang/psi/impl/mixins.kt:286]: Doesn't seem to be very practical to handle all of the cases, and fail hard.
