### PR TITLE
do not use backslash in import path (affects Windows only). fixes #390

### LINKED ISSUE #390: Wrong type of slashes in import on Windows
When we start to use a new contract in the code, the plugin highlights new name by yellow and suggests to add import of the contract at the beginning of the file. On Windows the suggestion looks like following:
```
Import file ...\libs\MyContract.sol
```
and result automatically added code is following
```
import "..\libs\MyContract.sol";
```
So, the plugin uses backward slashes \
But solidity requires forward slashes /, so it's necessary to manually fix the code to
```
import "../libs/MyContract.sol";
```
It would be nice if the plugin uses forward slashes initially.

### PR DESCRIPTION
**Pull request by mbolotov**

### CODE REVIEW

File: src/main/kotlin/me/serce/solidity/ide/inspections/fixes/ImportFileAction.kt [hunk 1]
```diff
@@ -127,7 +126,7 @@ class ImportFileAction(
 
     fun buildImportPath(source: VirtualFile, destination: VirtualFile): String {
       return Paths.get(source.path).parent.relativize(Paths.get(destination.path)).toString().let {
-        val separator = File.separator
+        val separator = "/"
```
Comment (SerCeMan) [inline src/main/kotlin/me/serce/solidity/ide/inspections/fixes/ImportFileAction.kt:129]: For my understanding, would this change be necessary considering the replace call? 

I haven't tested, but my understanding is that the hardcoded `/` here would break the `contains` calls below since they operate on relativized paths.

**Review by SerCeMan — APPROVED** [review]
Thanks 🙌

**Review by SerCeMan — APPROVED** [review]
Thanks 🙌
